name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - uses: actions/checkout@v2
      - run: go build
      - uses: golangci/golangci-lint-action@v2
      - run: go test -covermode atomic -coverprofile coverage.txt
      - uses: codecov/codecov-action@v1
      - run: go test -bench .
